version: '3'

services:
  cu-covid-db:
    image: mariadb:10.4
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - '3019:3306'
    volumes:
      - ./db/import.sql:/docker-entrypoint-initdb.d/import.sql
    environment:
      MYSQL_ROOT_PASSWORD: abcdef
      MYSQL_USER: api-user
      MYSQL_PASSWORD: abcdef
      MYSQL_DATABASE: CUCovid
    restart: always
